### PR TITLE
Translation improvement for home.page.message

### PR DESCRIPTION
**Pull request by gibbok**
Translation improvement for Italian language.

### CODE REVIEW

**Comment by MartinDoyleUK** [comment]
I've spoken to our Localisation department about this change, and it's not possible to merge this immediately. Please be patient while we confirm the change with them.

**Comment by gibbok** [comment]
Thanks for your update.

I would like to point out that the original text 'Home page' is fully compressible to the average Italian User even if clearly not written in their native language. 

Interestingly, If you look at how Google translates the term 'Home page' of their documentation you can see they have adopted 'Pagina iniziale'.

Example:
https://support.google.com/websearch/answer/463

Use the drop-down to switch to Italian.

**Comment by gbroadbent** [comment]
Thank you very much for the feedback.  We will take it into account and certainly place a note in our list of improvements.

Feedback is always most welcome.

Best regards,

Gloria Broadbent
Globalisation Manager
Tel: +44 1628 876517
Mobile: +44 07710 308292
Skype: gloria.broadbent

[Alfresco - Simple + Smart]<http://www.alfresco.com/>
[Alfresco]<http://www.alfresco.com/> [Twitter] <http://twitter.com/alfresco>  [Facebook] <http://www.facebook.com/alfrescosoftware>  [Feed] <http://blogs.alfresco.com/>  [LinkedIn] <http://www.linkedin.com/company/alfresco>  [YouTube] <http://www.youtube.com/alfresco101>

**Comment by draperd** [comment]
This has been discussed internally and it has been decided that to retain consistency across products and with other locales that the current value of "Home page" should be retained. We do appreciate you bringing this to our attention for consideration though.

**Comment by gibbok** [comment]
OK, it is comprehensible,  thanks for your message.

**Pull request closed without merging**
