### PR TITLE
Added dynamic update of label text to alfresco/html/Heading component

### PR DESCRIPTION
**Pull request by kevinroast**
Based on code for alfresco/html/Label that already does a similar job.

Uses the standard subscriptionTopic channel and updates the text of the inner heading node.

### CODE REVIEW

**Comment by draperd** [comment]
Spoken to Kev about this and he's going to make some updates to add a test and make a couple of minor changes - this shouldn't be pulled until after those changes have been added to the branch

**Comment by kevinroast** [comment]
Added intern test

**Comment by draperd** [comment]
Have re-done this as https://github.com/Alfresco/Aikau/pull/78 in order to address conflicts.

**Comment by kevinroast** [comment]
thanks!

**Pull request closed without merging**
