### PR TITLE
Add named window support to NavigationService

### PR DESCRIPTION
**Pull request by igorbga**
Add support to NavigationService so that it opens in a named window if the target is not NEW or CURRENT.

### CODE REVIEW

**Comment by draperd** [comment]
Could you please update this PR to include a unit test in accordance with the acceptance test criteria please. This will ensure that the capability you want to add will not be regressed accidentally in the future.

**Comment by draperd** [comment]
A couple of other things on this PR...

We want to do our best to have good JSDoc (I appreciate that we need to improve ourselves in this area) but one additional thing that would be good is for the JSDoc for the topic to be updated (see https://github.com/Alfresco/Aikau/blob/86f32f9c5777ccf17c832c6692dcb4232d3a8c11/aikau/src/main/resources/alfresco/core/topics.js#L619). This would mean that the online topics documentation (http://dev.alfresco.com/resource/docs/aikau-jsdoc/topics.html) describing the payload would indicate that named targets could be provided.

Finally (and I wouldn't reject a PR for it) but it would be really good if you could keep brackets consistent with the rest of the file :)

As I said, if you'd rather we make the changes then let me know and I'll raise the appropriate JIRA and add to our backlog.

**Comment by igorbga** [comment]
Sorry about the brackets, didn't notice the style difference.

I don't have much clue about how unit testing is done for Aikau so I think it will be better to raise a JIRA issue. I'll try to look to it when it is done to see if I get how to do it for future PRs.

Will you rise the issue yourself or should I raise it?

**Comment by draperd** [comment]
I've raised https://issues.alfresco.com/jira/browse/AKU-824 to cover this feature request. It's in the provisional plan for the sprint after next, so hopefully you'll have it in a couple of weeks - but as this is small we'll try and pull it into the next sprint if possible.

**Comment by igorbga** [comment]
Great Thanks

**Pull request closed without merging**
