### PR TITLE
AKU-694: Download Cancel is not canceling download

### PR DESCRIPTION
**Pull request by MartinDoyleUK**
This addresses [AKU-694](https://issues.alfresco.com/jira/browse/AKU-694) by changing the cancel-button publish from `ALF_CLOSE_DIALOG` to `ALF_PROGRESS_CANCELLED`. This automatically closes the dialog. Additionally, the cancel handler-function sets a flag to say that the task(s) have been cancelled and for the completion actions not to be run.

### CODE REVIEW

**Comment by draperd** [comment]
Has this been tested against Share at all yet? Or is this just unit test driven?

**Comment by MartinDoyleUK** [comment]
Just unit-tests

**Comment by draperd** [comment]
Code looks good though... I'm happy to merge, but would be good to get the sniff test against Share. I can do that if you like.

**Comment by MartinDoyleUK** [comment]
Thank you ... would be good if you could! :)

**Pull request merged**
